tap 'homebrew/cask'

#brews
brew 'git'
brew 'go'
brew 'awscli'
brew 'kubectl'

#casks
cask 'visual-studio-code'
cask 'iterm2'
cask 'postman'
cask 'slack'
cask 'zoom'
cask 'spotify'
cask 'skype'
cask 'grammarly'
cask 'docker'
cask 'authy'
cask 'google-chrome'
cask '1password'
cask 'intellij-idea'
cask 'brave-browser'
cask 'tunnelblick'
cask 'adobe-acrobat-reader'